//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBankX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenBankX.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement.
        /// </summary>
        public static string AddMeasurement {
            get {
                return ResourceManager.GetString("AddMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Tree.
        /// </summary>
        public static string AddNewTree {
            get {
                return ResourceManager.GetString("AddNewTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Plot.
        /// </summary>
        public static string AddPlot {
            get {
                return ResourceManager.GetString("AddPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pricing scheme.
        /// </summary>
        public static string AddPricing {
            get {
                return ResourceManager.GetString("AddPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Plot.
        /// </summary>
        public static string AddtoPlot {
            get {
                return ResourceManager.GetString("AddtoPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tree.
        /// </summary>
        public static string AddTree {
            get {
                return ResourceManager.GetString("AddTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Plot.
        /// </summary>
        public static string CreatePlot {
            get {
                return ResourceManager.GetString("CreatePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Plot.
        /// </summary>
        public static string DeletePlot {
            get {
                return ResourceManager.GetString("DeletePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tree.
        /// </summary>
        public static string DeleteTree {
            get {
                return ResourceManager.GetString("DeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter is invalid.
        /// </summary>
        public static string DiaInvalid {
            get {
                return ResourceManager.GetString("DiaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        public static string Earlier {
            get {
                return ResourceManager.GetString("Earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girth(cm).
        /// </summary>
        public static string Girth {
            get {
                return ResourceManager.GetString("Girth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height(m).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Length(m).
        /// </summary>
        public static string LogLength {
            get {
                return ResourceManager.GetString("LogLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Plots.
        /// </summary>
        public static string ManagePlots {
            get {
                return ResourceManager.GetString("ManagePlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Tree.
        /// </summary>
        public static string MeasureTree {
            get {
                return ResourceManager.GetString("MeasureTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchantable Height(m).
        /// </summary>
        public static string MerchHeight {
            get {
                return ResourceManager.GetString("MerchHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum diameter (cm).
        /// </summary>
        public static string minimumdiameter {
            get {
                return ResourceManager.GetString("minimumdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is invalid.
        /// </summary>
        public static string PriceInvalid {
            get {
                return ResourceManager.GetString("PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricings.
        /// </summary>
        public static string Pricings {
            get {
                return ResourceManager.GetString("Pricings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Plot.
        /// </summary>
        public static string SelectaPlot {
            get {
                return ResourceManager.GetString("SelectaPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Tree.
        /// </summary>
        public static string SelectaTree {
            get {
                return ResourceManager.GetString("SelectaTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Pricing Scheme.
        /// </summary>
        public static string SelectPricing {
            get {
                return ResourceManager.GetString("SelectPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size already exists.
        /// </summary>
        public static string SizeExists {
            get {
                return ResourceManager.GetString("SizeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Small.
        /// </summary>
        public static string TooSmall {
            get {
                return ResourceManager.GetString("TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Logs.
        /// </summary>
        public static string TotalLogs {
            get {
                return ResourceManager.GetString("TotalLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree ID.
        /// </summary>
        public static string TreeID {
            get {
                return ResourceManager.GetString("TreeID", resourceCulture);
            }
        }
    }
}
