//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBankX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenBankX.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add from Average.
        /// </summary>
        public static string AddAvg {
            get {
                return ResourceManager.GetString("AddAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement.
        /// </summary>
        public static string AddMeasurement {
            get {
                return ResourceManager.GetString("AddMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Merchantable Height.
        /// </summary>
        public static string AddMHeight {
            get {
                return ResourceManager.GetString("AddMHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Tree.
        /// </summary>
        public static string AddNewTree {
            get {
                return ResourceManager.GetString("AddNewTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Plot.
        /// </summary>
        public static string AddPlot {
            get {
                return ResourceManager.GetString("AddPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Plot  no pin.
        /// </summary>
        public static string AddPlotNoPin {
            get {
                return ResourceManager.GetString("AddPlotNoPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Price Bracket.
        /// </summary>
        public static string AddPriceB {
            get {
                return ResourceManager.GetString("AddPriceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pricing scheme.
        /// </summary>
        public static string AddPricing {
            get {
                return ResourceManager.GetString("AddPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Plot.
        /// </summary>
        public static string AddtoPlot {
            get {
                return ResourceManager.GetString("AddtoPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tree.
        /// </summary>
        public static string AddTree {
            get {
                return ResourceManager.GetString("AddTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to add trees to this plot?.
        /// </summary>
        public static string AddTree2 {
            get {
                return ResourceManager.GetString("AddTree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area not near pin.
        /// </summary>
        public static string Apin {
            get {
                return ResourceManager.GetString("Apin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Price.
        /// </summary>
        public static string ChangePrice {
            get {
                return ResourceManager.GetString("ChangePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Pricing.
        /// </summary>
        public static string ChangePricing {
            get {
                return ResourceManager.GetString("ChangePricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Edit.
        /// </summary>
        public static string ComfirmEn {
            get {
                return ResourceManager.GetString("ComfirmEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate.
        /// </summary>
        public static string ConvRate {
            get {
                return ResourceManager.GetString("ConvRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Plot.
        /// </summary>
        public static string CreatePlot {
            get {
                return ResourceManager.GetString("CreatePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        public static string CurrAdd {
            get {
                return ResourceManager.GetString("CurrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Currency.
        /// </summary>
        public static string CurrDel {
            get {
                return ResourceManager.GetString("CurrDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Currency: .
        /// </summary>
        public static string CurrenciesS {
            get {
                return ResourceManager.GetString("CurrenciesS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Currency.
        /// </summary>
        public static string CurrenciesSet {
            get {
                return ResourceManager.GetString("CurrenciesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to set this as the currency to use?.
        /// </summary>
        public static string CurrenciesSet2 {
            get {
                return ResourceManager.GetString("CurrenciesSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date exists.
        /// </summary>
        public static string DateExists {
            get {
                return ResourceManager.GetString("DateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement exists for this date.
        /// </summary>
        public static string DateExistsB {
            get {
                return ResourceManager.GetString("DateExistsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Made.
        /// </summary>
        public static string DateMade {
            get {
                return ResourceManager.GetString("DateMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure you want to delete?.
        /// </summary>
        public static string DelConf {
            get {
                return ResourceManager.GetString("DelConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Plot.
        /// </summary>
        public static string DeletePlot {
            get {
                return ResourceManager.GetString("DeletePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tree.
        /// </summary>
        public static string DeleteTree {
            get {
                return ResourceManager.GetString("DeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pricing Scheme.
        /// </summary>
        public static string DelPrice {
            get {
                return ResourceManager.GetString("DelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is in future.
        /// </summary>
        public static string DFute {
            get {
                return ResourceManager.GetString("DFute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter is invalid.
        /// </summary>
        public static string DiaInvalid {
            get {
                return ResourceManager.GetString("DiaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter (cm).
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Files, Please Wait..
        /// </summary>
        public static string DownloadPW {
            get {
                return ResourceManager.GetString("DownloadPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        public static string Earlier {
            get {
                return ResourceManager.GetString("Earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entry.
        /// </summary>
        public static string EditEn {
            get {
                return ResourceManager.GetString("EditEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Plot.
        /// </summary>
        public static string EditPlot {
            get {
                return ResourceManager.GetString("EditPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit measurement.
        /// </summary>
        public static string EMes {
            get {
                return ResourceManager.GetString("EMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid date.
        /// </summary>
        public static string EnterVDate {
            get {
                return ResourceManager.GetString("EnterVDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate All.
        /// </summary>
        public static string EvaluateAll {
            get {
                return ResourceManager.GetString("EvaluateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Location.
        /// </summary>
        public static string FLoc {
            get {
                return ResourceManager.GetString("FLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary requires at least 4 points..
        /// </summary>
        public static string fourpointBound {
            get {
                return ResourceManager.GetString("fourpointBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girth/Diameter.
        /// </summary>
        public static string GDBH {
            get {
                return ResourceManager.GetString("GDBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girth(cm).
        /// </summary>
        public static string Girth {
            get {
                return ResourceManager.GetString("Girth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height(m).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From Plot.
        /// </summary>
        public static string ImportPlot {
            get {
                return ResourceManager.GetString("ImportPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is invalid.
        /// </summary>
        public static string InputInv {
            get {
                return ResourceManager.GetString("InputInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is invalid.
        /// </summary>
        public static string IsInvalid {
            get {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude, Longitude.
        /// </summary>
        public static string Latlon {
            get {
                return ResourceManager.GetString("Latlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Details.
        /// </summary>
        public static string LessDetails {
            get {
                return ResourceManager.GetString("LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string LoadFail {
            get {
                return ResourceManager.GetString("LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Finished.
        /// </summary>
        public static string LoadingFin {
            get {
                return ResourceManager.GetString("LoadingFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log class.
        /// </summary>
        public static string LogClass {
            get {
                return ResourceManager.GetString("LogClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log length(m).
        /// </summary>
        public static string LogLength {
            get {
                return ResourceManager.GetString("LogLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Lon {
            get {
                return ResourceManager.GetString("Lon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Plots.
        /// </summary>
        public static string ManagePlots {
            get {
                return ResourceManager.GetString("ManagePlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Map.
        /// </summary>
        public static string MapAdd {
            get {
                return ResourceManager.GetString("MapAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum diameter(cm).
        /// </summary>
        public static string maxdiameter {
            get {
                return ResourceManager.GetString("maxdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value is too high.
        /// </summary>
        public static string MaxV {
            get {
                return ResourceManager.GetString("MaxV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value too high, please edit higher brackets first.
        /// </summary>
        public static string MaxV2 {
            get {
                return ResourceManager.GetString("MaxV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean diameter.
        /// </summary>
        public static string MeanD {
            get {
                return ResourceManager.GetString("MeanD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean growth over time.
        /// </summary>
        public static string MeanG {
            get {
                return ResourceManager.GetString("MeanG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean price.
        /// </summary>
        public static string MeanP {
            get {
                return ResourceManager.GetString("MeanP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean volume.
        /// </summary>
        public static string MeanV {
            get {
                return ResourceManager.GetString("MeanV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure All.
        /// </summary>
        public static string MeasureAll {
            get {
                return ResourceManager.GetString("MeasureAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure tree.
        /// </summary>
        public static string MeasureTree {
            get {
                return ResourceManager.GetString("MeasureTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchantable.
        /// </summary>
        public static string Merch {
            get {
                return ResourceManager.GetString("Merch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchantable height(m).
        /// </summary>
        public static string MerchHeight {
            get {
                return ResourceManager.GetString("MerchHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchantable Logs.
        /// </summary>
        public static string MerchLogs {
            get {
                return ResourceManager.GetString("MerchLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum diameter (cm).
        /// </summary>
        public static string minimumdiameter {
            get {
                return ResourceManager.GetString("minimumdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Plot.
        /// </summary>
        public static string NewPlot {
            get {
                return ResourceManager.GetString("NewPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new pricing scheme.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Plot has no prices. .
        /// </summary>
        public static string NoPrice {
            get {
                return ResourceManager.GetString("NoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points.
        /// </summary>
        public static string NotEnoughPoints {
            get {
                return ResourceManager.GetString("NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trees invalid.
        /// </summary>
        public static string NoTreeErr {
            get {
                return ResourceManager.GetString("NoTreeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plot has no trees..
        /// </summary>
        public static string NoTrees {
            get {
                return ResourceManager.GetString("NoTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Town.
        /// </summary>
        public static string NTown {
            get {
                return ResourceManager.GetString("NTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trees.
        /// </summary>
        public static string NumberTrees {
            get {
                return ResourceManager.GetString("NumberTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Logs.
        /// </summary>
        public static string NumLog {
            get {
                return ResourceManager.GetString("NumLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trees.
        /// </summary>
        public static string NumTree {
            get {
                return ResourceManager.GetString("NumTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Name.
        /// </summary>
        public static string OName {
            get {
                return ResourceManager.GetString("OName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates out of range..
        /// </summary>
        public static string OORCoord {
            get {
                return ResourceManager.GetString("OORCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or larger.
        /// </summary>
        public static string OrLarger {
            get {
                return ResourceManager.GetString("OrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is before plot is made.
        /// </summary>
        public static string PastTree {
            get {
                return ResourceManager.GetString("PastTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Here.
        /// </summary>
        public static string PinHere {
            get {
                return ResourceManager.GetString("PinHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is invalid.
        /// </summary>
        public static string PriceInvalid {
            get {
                return ResourceManager.GetString("PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricings.
        /// </summary>
        public static string Pricings {
            get {
                return ResourceManager.GetString("Pricings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a price scheme.
        /// </summary>
        public static string PSPrice {
            get {
                return ResourceManager.GetString("PSPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per USD.
        /// </summary>
        public static string PUSD {
            get {
                return ResourceManager.GetString("PUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edit.
        /// </summary>
        public static string SEdit {
            get {
                return ResourceManager.GetString("SEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a plot.
        /// </summary>
        public static string SelectaPlot {
            get {
                return ResourceManager.GetString("SelectaPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tree.
        /// </summary>
        public static string SelectaTree {
            get {
                return ResourceManager.GetString("SelectaTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a pricing scheme.
        /// </summary>
        public static string SelectPricing {
            get {
                return ResourceManager.GetString("SelectPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set area.
        /// </summary>
        public static string SetArea {
            get {
                return ResourceManager.GetString("SetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Boundary.
        /// </summary>
        public static string SetBoundary {
            get {
                return ResourceManager.GetString("SetBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to use a map or type in manually?.
        /// </summary>
        public static string SetBoundary2 {
            get {
                return ResourceManager.GetString("SetBoundary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string SetBoundaryA {
            get {
                return ResourceManager.GetString("SetBoundaryA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SetBoundaryB {
            get {
                return ResourceManager.GetString("SetBoundaryB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All On Map.
        /// </summary>
        public static string ShowAllOnMap {
            get {
                return ResourceManager.GetString("ShowAllOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot data.
        /// </summary>
        public static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size already exists.
        /// </summary>
        public static string SizeExists {
            get {
                return ResourceManager.GetString("SizeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        public static string SMap {
            get {
                return ResourceManager.GetString("SMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Added Successfully to Plot:.
        /// </summary>
        public static string SuccTree {
            get {
                return ResourceManager.GetString("SuccTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of Trees.
        /// </summary>
        public static string SumL1 {
            get {
                return ResourceManager.GetString("SumL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data by Log Class.
        /// </summary>
        public static string SumL2 {
            get {
                return ResourceManager.GetString("SumL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary per Plot.
        /// </summary>
        public static string SumL3 {
            get {
                return ResourceManager.GetString("SumL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows you data about the logs produced by this plot. Double tapping a log size will show a list of every log in that catagory and which tree it would come from..
        /// </summary>
        public static string SummaryTute {
            get {
                return ResourceManager.GetString("SummaryTute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too small.
        /// </summary>
        public static string TooSmall {
            get {
                return ResourceManager.GetString("TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total logs.
        /// </summary>
        public static string TotalLogs {
            get {
                return ResourceManager.GetString("TotalLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total volume (m³).
        /// </summary>
        public static string TotalVol {
            get {
                return ResourceManager.GetString("TotalVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree ID.
        /// </summary>
        public static string TreeID {
            get {
                return ResourceManager.GetString("TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees.
        /// </summary>
        public static string Trees {
            get {
                return ResourceManager.GetString("Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, welcome to the Greenbank tutorial. As you continue through the app, tutorials will pop up to help you..
        /// </summary>
        public static string TuteMenu0 {
            get {
                return ResourceManager.GetString("TuteMenu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the top of this page is the Sign in button. This will allow you to sign in to your Google account, once this is done you can upload your files to Google Drive and download them to any other device..
        /// </summary>
        public static string TuteMenu1 {
            get {
                return ResourceManager.GetString("TuteMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to mark the location of your plots.
        /// </summary>
        public static string TutePlot0 {
            get {
                return ResourceManager.GetString("TutePlot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pin can be placed on the map by either pressing on the map at the location you want or by pressing on the pin here button to place a pin at your location. Deleting plots can be done on the Manage Plots Page..
        /// </summary>
        public static string TutePlot1 {
            get {
                return ResourceManager.GetString("TutePlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you tap on the pin of a plot that already exists, you can then place pins that mark out the border of the plot..
        /// </summary>
        public static string TutePlot2 {
            get {
                return ResourceManager.GetString("TutePlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to create price schemes for your logs.
        /// </summary>
        public static string TutePrice0 {
            get {
                return ResourceManager.GetString("TutePrice0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pricing scheme consists of a name a log length and price brackets..
        /// </summary>
        public static string TutePrice1 {
            get {
                return ResourceManager.GetString("TutePrice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any logs smaller than the smallest bracket are worth nothing, any logs larger than the largest bracket will be priced the same as logs in the highest bracket..
        /// </summary>
        public static string TutePrice2 {
            get {
                return ResourceManager.GetString("TutePrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a price bracket is deleted, the bracket before it will expand to fill the gap..
        /// </summary>
        public static string TutePrice3 {
            get {
                return ResourceManager.GetString("TutePrice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Earlier&quot; and &quot;Later&quot; buttons change the data to the previous/next measurement that was made for that tree. The add measurement button allows you to add new measurement data for the tree..
        /// </summary>
        public static string TuteSum1 {
            get {
                return ResourceManager.GetString("TuteSum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Files, Please Wait..
        /// </summary>
        public static string UploadPW {
            get {
                return ResourceManager.GetString("UploadPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Waypoint.
        /// </summary>
        public static string WayAdd {
            get {
                return ResourceManager.GetString("WayAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Welcome to GreenBank. Please log In with a Google Account.
        /// </summary>
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GreenBank..
        /// </summary>
        public static string Welcome2 {
            get {
                return ResourceManager.GetString("Welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add coordinates in Lat, Long form.
        /// </summary>
        public static string WrongCoord {
            get {
                return ResourceManager.GetString("WrongCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year planted.
        /// </summary>
        public static string YPlant {
            get {
                return ResourceManager.GetString("YPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtube.com/embed/cvJW3ZghrrU.
        /// </summary>
        public static string zyoutube1 {
            get {
                return ResourceManager.GetString("zyoutube1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtube.com/embed/2QL01_wyCGI.
        /// </summary>
        public static string zyoutube2 {
            get {
                return ResourceManager.GetString("zyoutube2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtube.com/embed/7tlbBvQb8NU.
        /// </summary>
        public static string zyoutube3 {
            get {
                return ResourceManager.GetString("zyoutube3", resourceCulture);
            }
        }
    }
}
