//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBankX.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GreenBankX.Resources.AppResource.es", typeof(AppResource_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddAvg {
            get {
                return ResourceManager.GetString("AddAvg", resourceCulture);
            }
        }
        
        public static string AddMeasurement {
            get {
                return ResourceManager.GetString("AddMeasurement", resourceCulture);
            }
        }
        
        public static string AddMHeight {
            get {
                return ResourceManager.GetString("AddMHeight", resourceCulture);
            }
        }
        
        public static string AddNewTree {
            get {
                return ResourceManager.GetString("AddNewTree", resourceCulture);
            }
        }
        
        public static string AddPlot {
            get {
                return ResourceManager.GetString("AddPlot", resourceCulture);
            }
        }
        
        public static string AddPlotNoPin {
            get {
                return ResourceManager.GetString("AddPlotNoPin", resourceCulture);
            }
        }
        
        public static string AddPriceB {
            get {
                return ResourceManager.GetString("AddPriceB", resourceCulture);
            }
        }
        
        public static string AddPricing {
            get {
                return ResourceManager.GetString("AddPricing", resourceCulture);
            }
        }
        
        public static string AddtoPlot {
            get {
                return ResourceManager.GetString("AddtoPlot", resourceCulture);
            }
        }
        
        public static string AddTree {
            get {
                return ResourceManager.GetString("AddTree", resourceCulture);
            }
        }
        
        public static string AddTree2 {
            get {
                return ResourceManager.GetString("AddTree2", resourceCulture);
            }
        }
        
        public static string Apin {
            get {
                return ResourceManager.GetString("Apin", resourceCulture);
            }
        }
        
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        public static string ChangePrice {
            get {
                return ResourceManager.GetString("ChangePrice", resourceCulture);
            }
        }
        
        public static string ChangePricing {
            get {
                return ResourceManager.GetString("ChangePricing", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string ComfirmEn {
            get {
                return ResourceManager.GetString("ComfirmEn", resourceCulture);
            }
        }
        
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string ConvRate {
            get {
                return ResourceManager.GetString("ConvRate", resourceCulture);
            }
        }
        
        public static string CreatePlot {
            get {
                return ResourceManager.GetString("CreatePlot", resourceCulture);
            }
        }
        
        public static string CurrAdd {
            get {
                return ResourceManager.GetString("CurrAdd", resourceCulture);
            }
        }
        
        public static string CurrDel {
            get {
                return ResourceManager.GetString("CurrDel", resourceCulture);
            }
        }
        
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        public static string CurrenciesS {
            get {
                return ResourceManager.GetString("CurrenciesS", resourceCulture);
            }
        }
        
        public static string CurrenciesSet {
            get {
                return ResourceManager.GetString("CurrenciesSet", resourceCulture);
            }
        }
        
        public static string CurrenciesSet2 {
            get {
                return ResourceManager.GetString("CurrenciesSet2", resourceCulture);
            }
        }
        
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DateExists {
            get {
                return ResourceManager.GetString("DateExists", resourceCulture);
            }
        }
        
        public static string DateExistsB {
            get {
                return ResourceManager.GetString("DateExistsB", resourceCulture);
            }
        }
        
        public static string DateMade {
            get {
                return ResourceManager.GetString("DateMade", resourceCulture);
            }
        }
        
        public static string DelConf {
            get {
                return ResourceManager.GetString("DelConf", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeletePlot {
            get {
                return ResourceManager.GetString("DeletePlot", resourceCulture);
            }
        }
        
        public static string DeleteTree {
            get {
                return ResourceManager.GetString("DeleteTree", resourceCulture);
            }
        }
        
        public static string DelPrice {
            get {
                return ResourceManager.GetString("DelPrice", resourceCulture);
            }
        }
        
        public static string DFute {
            get {
                return ResourceManager.GetString("DFute", resourceCulture);
            }
        }
        
        public static string DiaInvalid {
            get {
                return ResourceManager.GetString("DiaInvalid", resourceCulture);
            }
        }
        
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string DownloadPW {
            get {
                return ResourceManager.GetString("DownloadPW", resourceCulture);
            }
        }
        
        public static string Earlier {
            get {
                return ResourceManager.GetString("Earlier", resourceCulture);
            }
        }
        
        public static string EditEn {
            get {
                return ResourceManager.GetString("EditEn", resourceCulture);
            }
        }
        
        public static string EditPlot {
            get {
                return ResourceManager.GetString("EditPlot", resourceCulture);
            }
        }
        
        public static string EMes {
            get {
                return ResourceManager.GetString("EMes", resourceCulture);
            }
        }
        
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        public static string EnterVDate {
            get {
                return ResourceManager.GetString("EnterVDate", resourceCulture);
            }
        }
        
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        public static string EvaluateAll {
            get {
                return ResourceManager.GetString("EvaluateAll", resourceCulture);
            }
        }
        
        public static string FLoc {
            get {
                return ResourceManager.GetString("FLoc", resourceCulture);
            }
        }
        
        public static string fourpointBound {
            get {
                return ResourceManager.GetString("fourpointBound", resourceCulture);
            }
        }
        
        public static string GDBH {
            get {
                return ResourceManager.GetString("GDBH", resourceCulture);
            }
        }
        
        public static string Girth {
            get {
                return ResourceManager.GetString("Girth", resourceCulture);
            }
        }
        
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        public static string ImportPlot {
            get {
                return ResourceManager.GetString("ImportPlot", resourceCulture);
            }
        }
        
        public static string InputInv {
            get {
                return ResourceManager.GetString("InputInv", resourceCulture);
            }
        }
        
        public static string IsInvalid {
            get {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        public static string Latlon {
            get {
                return ResourceManager.GetString("Latlon", resourceCulture);
            }
        }
        
        public static string LessDetails {
            get {
                return ResourceManager.GetString("LessDetails", resourceCulture);
            }
        }
        
        public static string LoadFail {
            get {
                return ResourceManager.GetString("LoadFail", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LoadingFin {
            get {
                return ResourceManager.GetString("LoadingFin", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string LogClass {
            get {
                return ResourceManager.GetString("LogClass", resourceCulture);
            }
        }
        
        public static string LogLength {
            get {
                return ResourceManager.GetString("LogLength", resourceCulture);
            }
        }
        
        public static string Lon {
            get {
                return ResourceManager.GetString("Lon", resourceCulture);
            }
        }
        
        public static string ManagePlots {
            get {
                return ResourceManager.GetString("ManagePlots", resourceCulture);
            }
        }
        
        public static string MapAdd {
            get {
                return ResourceManager.GetString("MapAdd", resourceCulture);
            }
        }
        
        public static string maxdiameter {
            get {
                return ResourceManager.GetString("maxdiameter", resourceCulture);
            }
        }
        
        public static string MaxV {
            get {
                return ResourceManager.GetString("MaxV", resourceCulture);
            }
        }
        
        public static string MaxV2 {
            get {
                return ResourceManager.GetString("MaxV2", resourceCulture);
            }
        }
        
        public static string MeanD {
            get {
                return ResourceManager.GetString("MeanD", resourceCulture);
            }
        }
        
        public static string MeanG {
            get {
                return ResourceManager.GetString("MeanG", resourceCulture);
            }
        }
        
        public static string MeanP {
            get {
                return ResourceManager.GetString("MeanP", resourceCulture);
            }
        }
        
        public static string MeanV {
            get {
                return ResourceManager.GetString("MeanV", resourceCulture);
            }
        }
        
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        public static string MeasureAll {
            get {
                return ResourceManager.GetString("MeasureAll", resourceCulture);
            }
        }
        
        public static string MeasureTree {
            get {
                return ResourceManager.GetString("MeasureTree", resourceCulture);
            }
        }
        
        public static string Merch {
            get {
                return ResourceManager.GetString("Merch", resourceCulture);
            }
        }
        
        public static string MerchHeight {
            get {
                return ResourceManager.GetString("MerchHeight", resourceCulture);
            }
        }
        
        public static string MerchLogs {
            get {
                return ResourceManager.GetString("MerchLogs", resourceCulture);
            }
        }
        
        public static string minimumdiameter {
            get {
                return ResourceManager.GetString("minimumdiameter", resourceCulture);
            }
        }
        
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        public static string NewPlot {
            get {
                return ResourceManager.GetString("NewPlot", resourceCulture);
            }
        }
        
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        public static string NoPrice {
            get {
                return ResourceManager.GetString("NoPrice", resourceCulture);
            }
        }
        
        public static string NotEnoughPoints {
            get {
                return ResourceManager.GetString("NotEnoughPoints", resourceCulture);
            }
        }
        
        public static string NoTreeErr {
            get {
                return ResourceManager.GetString("NoTreeErr", resourceCulture);
            }
        }
        
        public static string NoTrees {
            get {
                return ResourceManager.GetString("NoTrees", resourceCulture);
            }
        }
        
        public static string NTown {
            get {
                return ResourceManager.GetString("NTown", resourceCulture);
            }
        }
        
        public static string NumberTrees {
            get {
                return ResourceManager.GetString("NumberTrees", resourceCulture);
            }
        }
        
        public static string NumLog {
            get {
                return ResourceManager.GetString("NumLog", resourceCulture);
            }
        }
        
        public static string NumTree {
            get {
                return ResourceManager.GetString("NumTree", resourceCulture);
            }
        }
        
        public static string OName {
            get {
                return ResourceManager.GetString("OName", resourceCulture);
            }
        }
        
        public static string OORCoord {
            get {
                return ResourceManager.GetString("OORCoord", resourceCulture);
            }
        }
        
        public static string OrLarger {
            get {
                return ResourceManager.GetString("OrLarger", resourceCulture);
            }
        }
        
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        public static string PastTree {
            get {
                return ResourceManager.GetString("PastTree", resourceCulture);
            }
        }
        
        public static string PinHere {
            get {
                return ResourceManager.GetString("PinHere", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string PriceInvalid {
            get {
                return ResourceManager.GetString("PriceInvalid", resourceCulture);
            }
        }
        
        public static string Pricings {
            get {
                return ResourceManager.GetString("Pricings", resourceCulture);
            }
        }
        
        public static string PSPrice {
            get {
                return ResourceManager.GetString("PSPrice", resourceCulture);
            }
        }
        
        public static string PUSD {
            get {
                return ResourceManager.GetString("PUSD", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        public static string SEdit {
            get {
                return ResourceManager.GetString("SEdit", resourceCulture);
            }
        }
        
        public static string SelectaPlot {
            get {
                return ResourceManager.GetString("SelectaPlot", resourceCulture);
            }
        }
        
        public static string SelectaTree {
            get {
                return ResourceManager.GetString("SelectaTree", resourceCulture);
            }
        }
        
        public static string SelectPricing {
            get {
                return ResourceManager.GetString("SelectPricing", resourceCulture);
            }
        }
        
        public static string SetArea {
            get {
                return ResourceManager.GetString("SetArea", resourceCulture);
            }
        }
        
        public static string SetBoundary {
            get {
                return ResourceManager.GetString("SetBoundary", resourceCulture);
            }
        }
        
        public static string SetBoundary2 {
            get {
                return ResourceManager.GetString("SetBoundary2", resourceCulture);
            }
        }
        
        public static string SetBoundaryA {
            get {
                return ResourceManager.GetString("SetBoundaryA", resourceCulture);
            }
        }
        
        public static string SetBoundaryB {
            get {
                return ResourceManager.GetString("SetBoundaryB", resourceCulture);
            }
        }
        
        public static string ShowAllOnMap {
            get {
                return ResourceManager.GetString("ShowAllOnMap", resourceCulture);
            }
        }
        
        public static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string SizeExists {
            get {
                return ResourceManager.GetString("SizeExists", resourceCulture);
            }
        }
        
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        public static string SMap {
            get {
                return ResourceManager.GetString("SMap", resourceCulture);
            }
        }
        
        public static string SuccTree {
            get {
                return ResourceManager.GetString("SuccTree", resourceCulture);
            }
        }
        
        public static string SumL1 {
            get {
                return ResourceManager.GetString("SumL1", resourceCulture);
            }
        }
        
        public static string SumL2 {
            get {
                return ResourceManager.GetString("SumL2", resourceCulture);
            }
        }
        
        public static string SumL3 {
            get {
                return ResourceManager.GetString("SumL3", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string SummaryTute {
            get {
                return ResourceManager.GetString("SummaryTute", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string TooSmall {
            get {
                return ResourceManager.GetString("TooSmall", resourceCulture);
            }
        }
        
        public static string TotalLogs {
            get {
                return ResourceManager.GetString("TotalLogs", resourceCulture);
            }
        }
        
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        public static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        public static string TotalVol {
            get {
                return ResourceManager.GetString("TotalVol", resourceCulture);
            }
        }
        
        public static string TreeID {
            get {
                return ResourceManager.GetString("TreeID", resourceCulture);
            }
        }
        
        public static string Trees {
            get {
                return ResourceManager.GetString("Trees", resourceCulture);
            }
        }
        
        public static string TuteMenu0 {
            get {
                return ResourceManager.GetString("TuteMenu0", resourceCulture);
            }
        }
        
        public static string TuteMenu1 {
            get {
                return ResourceManager.GetString("TuteMenu1", resourceCulture);
            }
        }
        
        public static string TutePlot0 {
            get {
                return ResourceManager.GetString("TutePlot0", resourceCulture);
            }
        }
        
        public static string TutePlot1 {
            get {
                return ResourceManager.GetString("TutePlot1", resourceCulture);
            }
        }
        
        public static string TutePlot2 {
            get {
                return ResourceManager.GetString("TutePlot2", resourceCulture);
            }
        }
        
        public static string TutePrice0 {
            get {
                return ResourceManager.GetString("TutePrice0", resourceCulture);
            }
        }
        
        public static string TutePrice1 {
            get {
                return ResourceManager.GetString("TutePrice1", resourceCulture);
            }
        }
        
        public static string TutePrice2 {
            get {
                return ResourceManager.GetString("TutePrice2", resourceCulture);
            }
        }
        
        public static string TutePrice3 {
            get {
                return ResourceManager.GetString("TutePrice3", resourceCulture);
            }
        }
        
        public static string TuteSum1 {
            get {
                return ResourceManager.GetString("TuteSum1", resourceCulture);
            }
        }
        
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        public static string UploadPW {
            get {
                return ResourceManager.GetString("UploadPW", resourceCulture);
            }
        }
        
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        public static string WayAdd {
            get {
                return ResourceManager.GetString("WayAdd", resourceCulture);
            }
        }
        
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        public static string Welcome2 {
            get {
                return ResourceManager.GetString("Welcome2", resourceCulture);
            }
        }
        
        public static string WrongCoord {
            get {
                return ResourceManager.GetString("WrongCoord", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        public static string YPlant {
            get {
                return ResourceManager.GetString("YPlant", resourceCulture);
            }
        }
    }
}
